name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: superbot
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build all services
        run: docker-compose build

      - name: Run tests (trading)
        run: |
          pip install -r trading/requirements.txt
          pytest trading/test_main.py

      - name: Lint (trading)
        run: |
          pip install flake8
          flake8 trading/

      # Adicione etapas para outros serviços conforme necessário

  # Deploy automatizado (opcional)
  # deploy:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy via SSH, Railway, Render, etc.
  #       run: echo "Deploy automático aqui" 